server:
  port: ${SERVER_PORT:9090}

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    root: warn
    com.quizze.quizze: info

management:
  endpoint:
    health:
      show-details: never
